language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.4

before_script: composer install
script: vendor/bin/phpunit --verbose --colors --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.xml

notifications:
  email: "timur.shagiakhmetov@corp.badoo.com"
